travis:
  secure:
    BINSTAR_TOKEN: TRjRnOdrPRP4F1qGy82O1TgRtIg92xZzfuGlbSXwsKH+hFekU7KInNR3vzRN8xcC2ze3kkUVjxJ+LG51HEp6sObjBulCZ5nsOs8qm/4FToFNv1kw8mwsS+Fe9HONRmDaNXeaLjUGkHUktHSbcv5CXrp5xRjqs4zYAmZcKy1C6rlfyfdKNA6Vq5z5kHJLev0F5vvs0hHgoV+h0l3XbIwdEaFpErUDb3ELKOhPash8pEXT+wMZjFezyZFAhfPXZdE+yS2vBIW5B5h/0iIoVAIBlzYFedJjNfqs++srIKK7Wf4AnxaCiKow3LBHicCtMPCjDL3fNLLjCZfU0g1juNNQR0boGTjUxmHYwL0RC56EmriJ9QO6R6Z1ee3yhyVdU5nOawlI1UR2f2IVsRckHEl9XE3tEwaNBKQ4Rj91pefezAucR+7CbdFdjp4oN0OQsAsssxinNt6acd6xWcC/yZ++WzJFcT2gCZWppzzu+kw8qqVXBvONTlDHr9OB1HXP9AW8/42k0+R2o89inJFUbSYbTMjtfdGHhsRDJgBEDLkCKoJGHf9uQWnTXNRrChyzweeMGHD8amghegUQwcE6L8x1D/0GgYiOUnmDREgzf9/vTz3E0vdvh4mf4wlO8D7ZrsBEIqlN4E0/wdbN0OAR8IQASn6pLY7kDTFQ2qP1UFMa9ao=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
